[package]
name = "arrayify"
version = "0.1.1"
edition = "2024"

[dependencies]
csv = "1.1"
clap = { version = "4.0", features = ["derive"] }
regex = "1"
tempfile = "3.17.1"

[[bin]]
name = "arrayify"
path = "src/main.rs"